---
- name: Install Jenkins | Add Jenkins repository key
  apt_key:
    url: "https://pkg.jenkins.io/debian/jenkins-ci.org.key"
    state: present
  ignore_errors: true

- name: "Install Jenkins - Check if jenkins.list exists"
  stat: path="/etc/apt/sources.list.d/jenkins.list"
  register: result

- name: Install Jenkins | Add apt repo
  command: "sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'"
  when: (not result.stat.exists)

- name: Install Jenkins | Install Jenkins from apt
  apt: 
    name: jenkins 
    state: present
    update_cache: yes 
    cache_valid_time: 86400

- name: Install Nginx 
  apt: 
    name: nginx 
    state: present

- name: Ensure nginx default config removed
  file: 
    path: /etc/nginx/sites-available
    state: absent

- name: Ensure Jenkins nginx config present
  copy: src="{{item}}" dest="/etc/nginx/sites-available/" owner="root" group="root" mode="0644" backup=yes
  with_items:
    - "jenkins"
  register: result
  
- name: Restart nginx
  service: name="nginx" state=restarted
  when: result.changed
  ignore_errors: true 