---

- name: Install Docker | Install support packages apt-transport-https
  apt: 
    name: apt-transport-https
    state: present

- name: Install Docker | Install support packages ca-certificates
  apt: 
    name: ca-certificates
    state: present

- name: Install Docker | Install support packages curl 
  apt: 
    name: curl 
    state: present  

- name: Install Docker | Install support packages software-properties-common 
  apt: 
    name: software-properties-common 
    state: present  

- name: Install Docker | Add Docker repository key
  apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  ignore_errors: true

- name: Install Docker | Add apt repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present


- name: Install Docker | Apt update  
  apt: 
    state: present
    update_cache: yes 
    cache_valid_time: 86400

- name: Install Docker | Install Docker CE 
  apt: 
    name: sudo apt-get install docker-ce 
    state: present
    update_cache: yes 


